services:
  api_db:
    build: ./BBDD
    restart: always
    ports:
      - 3307:3306
    networks:
      - api_network
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  
  php:
    build: ./PHP
    expose:
      - "9000"
    volumes:
      - ./app-res:/var/www/html

  nginx:
    build: ./NGINX
    ports:
      - "444:444"
    volumes:
      - ./app-res:/var/www/html
    depends_on:
      - php
  # php:
  #   build: ./PHP
  #   restart: always
  #   networks:
  #     - api_network
  #   volumes:
  #     - ./Apache/apacheUtils:/usr/local/apache2/htdocs

  # apache:
  #   build: ./Apache/
  #   restart: always
  #   ports: 
  #     - 8080:80
  #     - 443:443
  #   networks:
  #     - api_network
  #   depends_on:
  #     - php
  
  

  api:
    build: ./Backend/deckup/
    restart: always
    ports:
      - 8888:8888
    depends_on:
      - api_db
    networks:
      - api_network
    environment:
      - spring.datasource.url=jdbc:mysql://api_db:3306/deckup
      - spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

  web:
    build: ./Frontend/deckup/
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    networks:
      - api_network

networks:
  api_network:

volumes:
  mysql-data: